[package]
name = "edsm-stat-parser"
version = "0.1.0"
authors = ["Sri Ramanujam"]
edition = "2018"

[dependencies]
serde_json = "1.0.57"
serde = { version = "1.0.116", features = [ "derive" ] }
rayon = "1.4.0"
